### PR TITLE
renamed title screen sprites

### PR DESCRIPTION
**Pull request by Tianmaru**
For me, it was really confusing to edit the title screen, because each file was still named after its unknown symbol. So I renamed almost everything in `graphics/title_screen` in accordance with the symbols used in `src/graphics.c` and `src/title_screen.c`. Now that I think about it, I feel kind of dumb - surely you have some kind of automatic process to update symbols? If not, I would be glad to contribute to pokefirered!

### CODE REVIEW

**Comment by GriffinRichards** [comment]
This fails to build (you've renamed `unk_83bf79c` two different ways). And no there's nothing automatic set up to update symbol names, that's just the process of documentation. All the Gen III repos are still in-progress for documentation, so contributions are welcome

**Comment by Tianmaru** [comment]
Hey GriffinRichards, yeah, I noticed that too. I messed up with the fire and leave sprites. Working on a fix.

**Comment by Tianmaru** [comment]
Honestly, I don't know why the build is failing. After correcting the obvious error, apparently different ROMs are build so the comparison fails. Maybe I made another mistake and mixed two sprites up? But I double checked and couldn't find anything wrong. Maybe I will just give up on this.

**Comment by GriffinRichards** [comment]
Yeah it's failing because it doesn't match the original rom. See `graphics_file_rules.mk`, make sure to update the rules for the files you renamed

**Comment by Tianmaru** [comment]
Finally the build passed - this took me way longer than it should have. Thanks for your time and patience!

**Pull request merged**
