### PR TITLE
README: freenode is dead

### PR DESCRIPTION
**Pull request by rofl0r**

### CODE REVIEW

**Comment by rofl0r** [comment]
bonus: after applying it, you can do `git format-patch HEAD~1` and then `git am 0001-.....patch` in all the other pret repos, should apply there just as well.

**Comment by GriffinRichards** [comment]
Naturally people are welcome to chat anywhere about the project, but they don't necessarily need to be listed in the README. How many users of this project are at the suggested alternative? How many contributors? The sudden activity from people who apparently use GitHub but haven't made use of a fork of any pret repo is especially odd.

**Comment by rofl0r** [comment]
there's currently only 20 people in the chatroom, which is kinda expected as it's not announced anywhere and freenode has been almost (and now entirely) dead for the past 6 months - only people that saw libera as the legitimate successor to freenode have moved over.

the intent of this PR was not to start a discussion whether IRC is needed at all (obviously, it still is), but just to right a wrong.

**Comment by PikalaxALT** [comment]
The irc channel is completely defunct anyway so the link should be removed entirely or replaced with the Discord invite.

**Comment by rofl0r** [comment]
> The irc channel is completely defunct anyway so the link should be removed entirely

it's defunct precisely because it leads into nirvana. fixing it to point to where it actually is will most likely revive it as people that prefer IRC can find it again.

**Comment by PikalaxALT** [comment]
> > The irc channel is completely defunct anyway so the link should be removed entirely
> 
> it's defunct precisely because it leads into nirvana. fixing it to point to where it actually is will most likely revive it as people that prefer IRC can find it again.

It's defunct because it is not used by the repository maintainers.

Closing because this is a non-starter.

**Pull request closed without merging**
