### PR TITLE
Sync trainer_type/trainer_sight/var_value data type

### PR DESCRIPTION
**Pull request by GriffinRichards**
Porymap expects these values to be strings. As ints porymap will read/overwrite them as ""

### CODE REVIEW

**Comment by PikalaxALT** [comment]
Why not fix Porymap?

**Comment by GriffinRichards** [comment]
Trying to avoid large changes to pokeemerald, which is more widely used

**Comment by GriffinRichards** [comment]
Plus it requires fewer changes if we decided to use constants in the future

**Comment by PikalaxALT** [comment]
I mean, why not change porymap to accept both types, or interpret "" as 0?

**Comment by GriffinRichards** [comment]
Why make a change to porymap in order to maintain an unnecessary difference between the repos?

**Comment by PikalaxALT** [comment]
Why change 359 files in one project when you can change one file in another to solve the same problem?

**Comment by GriffinRichards** [comment]
Does the number of changed files really matter? It's still a minor change. pokeemerald treats these as strings, so we're either making the same change in the more popular repo or leaving a confusing inconsistency

**Comment by GriffinRichards** [comment]
Reposting from Discord just for tracking the conversation. But in this PR I'm not going to define macros for any of these fields. The `var_value` field especially, given that their values can be relative to the individual trigger var. This is just meant for porymap support right now. They're string ints in pokeemerald, porymap handles them this way already, and we can add constants to them later.

**Comment by GriffinRichards** [comment]
You're welcome to create constants for the triggers and trainer types and create an interim patch to porymap if you'd like.

**Pull request merged**
